{{- if not .Values.mariadb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.mariadb.fullname" . }}
  labels:
    app.kubernetes.io/name: matomo-mariadb
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.username | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | quote }}
{{- end }}
