{{- if and .Values.overseer.enabled .Values.overseer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blog-engine.fullname" . }}-overseer
  labels:
    {{- include "blog-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: overseer
  {{- with .Values.overseer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.overseer.ingress.className }}
  ingressClassName: {{ .Values.overseer.ingress.className }}
  {{- end }}
  {{- if .Values.overseer.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.overseer.ingress.host | quote }}
      secretName: {{ .Values.overseer.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.overseer.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "blog-engine.fullname" . }}-overseer
                port:
                  number: {{ .Values.overseer.service.port }}
{{- end }}
