{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blog-engine.serviceAccountName" . }}
  labels:
    {{- include "blog-engine.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
