apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  namespace: app-mailer
  labels: { app: mailer }
spec:
  replicas: 1
  selector:
    matchLabels: { app: mailer }
  template:
    metadata:
      labels: { app: mailer }
    spec:
      containers:
        - name: mailer
          image: ghcr.io/justcallmegreg/blog-mailer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef: { name: mailer-secrets }
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests: { cpu: 10m, memory: 64Mi }
            limits: { cpu: 250m, memory: 192Mi }
